update nginx config

diff --git a/.github/workflows/backend-deploy.yaml b/.github/workflows/backend-deploy.yaml
--- a/.github/workflows/backend-deploy.yaml
+++ b/.github/workflows/backend-deploy.yaml
@@ -182,7 +182,7 @@ jobs:
 
 
             echo "Testing and restarting Nginx..."
-            sudo nginx -t && sudo systemctl restart nginx || { echo "Nginx configuration failed!"; exit 1; }
+            sudo systemctl restart nginx || { echo "Nginx configuration failed!"; exit 1; }
 
             echo "Installing Certbot and requesting SSL certificate..."
             if ! command -v certbot &> /dev/null; then
@@ -191,6 +191,8 @@ jobs:
             fi
 
             sudo certbot --nginx --non-interactive --agree-tos --email "$CERTBOT_EMAIL" -d "$API_DOMAIN" -d "$WEB_DOMAIN"
+
+            sudo nginx -t || { echo "Nginx configuration test failed!"; exit 1; }
 
             echo "Reloading Nginx with SSL..."
             sudo nginx -t && sudo systemctl reload nginx
